version: '3.7'

networks:
  myNetwork:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=oracle
      - DB_PORT=1521
      - DB_USER=system
      - DB_PASSWORD=oracle
      - DB_SERVICE=mydb
    networks:
      - myNetwork
    volumes:
      - ./src:/app/src

volumes:
  oracle_data:
  oracle_fast_recovery_area:
